### ISSUE TITLE
Add to Melpa?

### ISSUE THREAD

**Issue by wyuenho** [karthink/timeout#2]
Hey,

Thanks for this package. This is incredibly useful as it's not only generic but takes care of many use cases. Arguably one the the most long-standing missing feature in Emacs. Would you mind submitting to Melpa?

Thanks

**Comment by karthink** [comment]
@wyuenho Sure, but I don't have the bandwidth right now to go through the MELPA submission process as I'm juggling too many other Emacs projects.  If you want to take it up that would be welcome.

I also considered submitting it to Emacs, but those tend to lead to long discussions, _i.e._ much more work than submitting to MELPA.  I'd have to first make a case for why you need something like this.  So there are no plans to do that either.

**Comment by wyuenho** [comment]
> I also considered submitting it to Emacs, but those tend to lead to long discussions

Don't worry I'm not going to put you thru this pain :)

I'll open a PR on Melpa soon.
